# Generated by Django 4.2.6 on 2024-03-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_blogpost_bodyimage_alter_blogpost_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=20)),
                ('team2', models.CharField(max_length=20)),
                ('start_time', models.DateTimeField()),
                ('team1Logo', models.ImageField(upload_to='team_logos')),
                ('team2Logo', models.ImageField(upload_to='team_logos')),
                ('competition', models.CharField(max_length=40)),
                ('matchday', models.CharField(max_length=30)),
            ],
        ),
    ]
