# Generated by Django 4.2.6 on 2024-03-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_match'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.AddField(
            model_name='match',
            name='match_link',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1Logo',
            field=models.ImageField(upload_to='team_logos/'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2Logo',
            field=models.ImageField(upload_to='team_logos/'),
        ),
    ]
