# Generated by Django 4.2.6 on 2024-03-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_match_options_match_match_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='alt_link1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='match',
            name='alt_link2',
            field=models.TextField(blank=True),
        ),
    ]
