# Generated by Django 4.2.6 on 2024-03-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_match_alt_link1_match_alt_link2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='alt_link1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='match',
            name='alt_link2',
            field=models.TextField(blank=True, default=''),
        ),
    ]
